CC=gcc
CFLAGS=-O2 -ggdb -Wall -I. -Werror --std=gnu11

GEN_HEADERS=op_enum.h op_str.h op_switch.h nativefuns.h
OBJ=prog.o custom.o stack.o vstack.o val/str.o val/num.o val/arr.o val/real.o val/val.o val/map.o vars.o
LIBS=

all: vm main

vm: vm.o libvm3.a
	$(CC) -o $@ $^ $(LIBS)

main: main.o libvm3.a
	$(CC) -o $@ $^ $(LIBS)

libvm3.a: $(OBJ) op_enum.h op_switch.h op_str.h
	ar -rc libvm3.a $(OBJ)

$(OBJ) vm.o main.o: $(GEN_HEADERS)

$(GEN_HEADERS) &: $(wildcard *.c) mkincludes.sh
	./mkincludes.sh

clean:
	rm -f $(OBJ) vm main vm.o libvm3.a main.o

.PHONY: all clean
